version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: profiles_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: features_user
      POSTGRES_PASSWORD: features_password
      POSTGRES_DB: features_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initial_database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U features_user -d features_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Added pgadmin for easier database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: profiles_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  featuresprovider:
    # ... other settings ...
    environment:
      - DB_HOST=features_db  # Use the service name here
      - DB_PORT=5432
      - DB_USER=features_user
      - DB_PASSWORD=features_password
      - DB_NAME=features_db

volumes:
  postgres_data:
  pgadmin_data: