version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: profiles_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: features_user
      POSTGRES_PASSWORD: features_password
      POSTGRES_DB: features_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initial_database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U features_user -d features_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
