openapi: 3.0.3
info:
  title: TrackMyOffer Feature Provider
  description: API for executing some AI-powered features
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /:
    get:
      summary: Root endpoint
      description: Returns a simple hello message
      operationId: root
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello"

  /greet:
    post:
      summary: Generate greeting
      description: Generates an AI-powered greeting for a given name
      operationId: greet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: "John"
      responses:
        '200':
          description: Successful greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, John!"
        '400':
          description: Bad request - name is missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Name is required"
        '503':
          description: AI service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "AI service is currently unavailable"

  /api/profile:
    post:
      summary: Create or update profile
      description: Creates a new profile or updates existing one if email already exists
      operationId: createOrUpdateProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileCreate'
      responses:
        '201':
          description: Profile created or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                        msg:
                          type: string
                        type:
                          type: string

  /api/extract-job-description:
    post:
      summary: Extract job description
      description: Extracts and processes job description from a provided URL
      operationId: extractJobDescription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jobDescriptionLink
              properties:
                jobDescriptionLink:
                  type: string
                  format: uri
                  example: "https://example.com/job-posting"
      responses:
        '200':
          description: Successfully extracted job description
          content:
            application/json:
              schema:
                type: object
                description: Extracted and processed job description data
        '400':
          description: Bad request - invalid or missing job description URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Invalid job description URL"
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Service is currently unavailable"

  /api/match-position:
    post:
      summary: Match position
      description: Analyzes a job description and returns matching information
      operationId: matchPosition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - profileId
                - jobDescription
              properties:
                profileId:
                  type: integer
                  description: ID of the user profile
                  example: 1
                jobDescription:
                  type: object
                  description: Job description data
              description: Job description data extracted from /extract-job-description
      responses:
        '200':
          description: Successfully matched position
          content:
            application/json:
              schema:
                type: object
                description: Job matching analysis result
        '400':
          description: Bad request - invalid job description data
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Invalid job description data"
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Service is currently unavailable"

  /api/build-cv:
    post:
      summary: Build CV
      description: Generates a customized CV based on a job description
      operationId: buildCV
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - profileId
                - jobDescription
              properties:
                profileId:
                  type: integer
                  description: ID of the user profile
                  example: 1
                jobDescription:
                  type: object
                  description: Job description data
              description: Job description data extracted from /extract-job-description
      responses:
        '200':
          description: Successfully built CV
          content:
            application/json:
              schema:
                type: object
                description: Generated CV content
        '400':
          description: Bad request - invalid job description data
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Invalid job description data"
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Service is currently unavailable"

  /api/generate-motivational-letter:
    post:
      summary: Generate motivational letter
      description: Creates a customized motivational letter based on a job description
      operationId: generateMotivationalLetter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - profileId
                - jobDescription
              properties:
                profileId:
                  type: integer
                  description: ID of the user profile
                  example: 1
                jobDescription:
                  type: object
                  description: Job description data
                textStyle:
                  type: string
                  description: Style preference for the motivational letter
                  example: "professional"
                notes:
                  type: string
                  description: Additional notes to include in the letter
                  example: "Please emphasize my leadership skills"
              description: Job description data extracted from /extract-job-description with optional style and notes
      responses:
        '200':
          description: Successfully generated motivational letter
          content:
            application/json:
              schema:
                type: object
                description: Generated motivational letter content
        '400':
          description: Bad request - invalid job description data
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Invalid job description data"
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Service is currently unavailable"

components:
  schemas:
    ProfileCreate:
      type: object
      required:
        - first_name
        - last_name
        - email
        - city
        - state
        - country
      properties:
        first_name:
          type: string
          minLength: 1
          maxLength: 100
        last_name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
        phone:
          type: string
          maxLength: 20
        city:
          type: string
          minLength: 1
          maxLength: 100
        state:
          type: string
          minLength: 1
          maxLength: 100
        country:
          type: string
          minLength: 1
          maxLength: 100
        summary:
          type: string
          nullable: true

    ProfileResponse:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
          nullable: true
        city:
          type: string
        state:
          type: string
        country:
          type: string
        summary:
          type: string
          nullable: true

    EducationCreate:
      type: object
      required:
        - institution
        - degree
        - start_date
      properties:
        institution:
          type: string
          minLength: 1
          maxLength: 255
        degree:
          type: string
          minLength: 1
          maxLength: 255
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
          nullable: true
        additional_info:
          type: string
          nullable: true

    SocialMediaCreate:
      type: object
      properties:
        linkedin_url:
          type: string
          maxLength: 255
          nullable: true
        github_url:
          type: string
          maxLength: 255
          nullable: true
        personal_website:
          type: string
          maxLength: 255
          nullable: true
        other_links:
          type: object
          additionalProperties:
            type: string
          nullable: true
