openapi: 3.0.3
info:
  title: TrackMyOffer Feature Provider
  description: API for executing some AI-powered features
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /:
    get:
      summary: Root endpoint
      description: Returns a simple hello message
      operationId: root
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello"

  /greet:
    post:
      summary: Generate greeting
      description: Generates an AI-powered greeting for a given name
      operationId: greet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: "John"
      responses:
        '200':
          description: Successful greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, John!"
        '400':
          description: Bad request - name is missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Name is required"
        '503':
          description: AI service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "AI service is currently unavailable"

components:
  schemas: {}