openapi: 3.0.3
info:
  title: TrackMyOffer Backend API
  description: |
    This is the API specification for the TrackMyOffer backend service.
    The service provides endpoints for the web interface and communicates with the feature service.
  version: 0.0.1
  contact:
    name: TrackMyOffer Team
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /v0/:
    get:
      summary: Root endpoint
      description: Returns a simple greeting message
      operationId: getRoot
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello World!"
  /v0/hello:
    get:
      summary: Hello endpoint
      description: Returns a greeting with the request origin
      operationId: getHello
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, 0:0:0:0:0:0:0:1:52788"
  /features/v0/hello:
    get:
      summary: Feature hello endpoint
      description: Calls the feature provider service to get a greeting
      operationId: getFeatureHello
      parameters:
        - name: name
          in: query
          description: The name to include in the greeting.
          required: true
          schema:
            type: string
            example: "Mark Ipatov"
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: "Hello from feature provider!"
        '400':
          description: Missing required query parameter "name"
          content:
            text/plain:
              schema:
                type: string
                example: "Missing query parameter: name"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Error calling feature provider"
  /features/v0/match-position:
    get:
      summary: Match position endpoint
      description: Analyzes a job description and returns matching information
      operationId: matchPosition
      parameters:
        - name: jobDescriptionLink
          in: query
          description: URL link to the job description to analyze
          required: true
          schema:
            type: string
            format: uri
            example: "https://example.com/job-posting"
        - name: profileId
          in: query
          description: ID of the user profile
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                description: Job matching analysis result
        '400':
          description: Missing required query parameter
          content:
            text/plain:
              schema:
                type: string
                example: "Missing jobDescriptionLink parameter"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Error processing job description"
  /features/v0/build-cv:
    get:
      summary: Build CV endpoint
      description: Generates a customized CV based on a job description
      operationId: buildCV
      parameters:
        - name: jobDescriptionLink
          in: query
          description: URL link to the job description to analyze
          required: true
          schema:
            type: string
            format: uri
            example: "https://example.com/job-posting"
        - name: profileId
          in: query
          description: ID of the user profile
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                description: Generated CV content
        '400':
          description: Missing required query parameter
          content:
            text/plain:
              schema:
                type: string
                example: "Missing jobDescriptionLink parameter"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Error generating CV"
  /features/v0/generate-motivational-letter:
    get:
      summary: Generate motivational letter endpoint
      description: Creates a customized motivational letter based on a job description
      operationId: generateMotivationalLetter
      parameters:
        - name: jobDescriptionLink
          in: query
          description: URL link to the job description to analyze
          required: true
          schema:
            type: string
            format: uri
            example: "https://example.com/job-posting"
        - name: textStyle
          in: query
          description: Style preference for the motivational letter
          required: false
          schema:
            type: string
            example: "professional"
        - name: notes
          in: query
          description: Additional notes to include in the letter
          required: false
          schema:
            type: string
            example: "Please emphasize my leadership skills"
        - name: profileId
          in: query
          description: ID of the user profile
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                description: Generated motivational letter content
        '400':
          description: Missing required query parameter
          content:
            text/plain:
              schema:
                type: string
                example: "Missing jobDescriptionLink parameter"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "Error generating motivational letter"
components:
  schemas: {}
