name: Features Provider Tests

on:
  push:
    paths:
      - 'FeaturesProvider/**'
      - '.github/workflows/features.yaml'
  pull_request:
    paths:
      - 'FeaturesProvider/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FeaturesProvider

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: pytest